### ISSUE TITLE
what am I missing on AlmaLinux?

### ISSUE THREAD

**Issue by escozul** [natelandau/dotfiles#15]
It's impossible to install it on almalinux. 
Keep getting this error after `chezmoi update` or `apply`
`chezmoi: .chezmoiscripts/install_nanorc.sh: fork/exec /tmp/3207797074.install_nanorc.sh: permission denied` but nothing seems to circumvent that.

I kept getting this for all chezmoi scripts so I installed the other files, and nanorc but I still get stuck there. I have no issues installing on ubuntu. Just Alma...

**Comment by SkimmSkimm** [comment]
Wish I could help but I don't use Almalinux and don't plan to support it.  My only recommendation would be to fork the repository and remove/edit whatever isn't working for you.

**Comment by natelandau** [comment]
Wish I could help but I don't use Almalinux and don't plan to support it. My only recommendation would be to fork the repository and remove/edit whatever isn't working for you.
